(function($){var xataface={};xataface.RecordBrowser=function(o){this.table=null;this.value=null;this.text=null;this.filters={};this.callback=null;this.el=document.createElement('div');this.baseURL=DATAFACE_URL+'/js/RecordBrowser';for(var i in o){this[i]=o[i];}
this.dirty=true;$('head').append('<link rel="stylesheet" type="text/css" href="'+DATAFACE_URL+'/css/smoothness/jquery-ui-1.7.2.custom.css"/>');}
xataface.RecordBrowser.prototype={display:function(){var rb=this;$('body').append(this.el);$(this.el).load(this.baseURL+'/templates/RecordBrowser.html',function(){var dialog=this;var searchChangeHandler=function(){rb.filterRecords({'-search':$(this).val()});};$(this).find('.xf-RecordBrowser-search-field').keyup(searchChangeHandler).change(searchChangeHandler);$(this).find('.xf-RecordBrowser-select-field').css('width','100%').attr('size',8);$(this).find('.xf-RecordBrowser-addnew-button').RecordDialog({table:rb.table,callback:function(){rb.dirty=true;rb.updateRecords();}});$(this).dialog({'title':'Select Record','buttons':{'Select':function(){var out={};$(dialog).find('.xf-RecordBrowser-select-field :selected').each(function(i,selected){out[$(selected).attr('value')]=$(selected).text();});if(rb.callback)rb.callback(out);$(this).dialog("close");},'Cancel':function(){$(this).dialog("close");}},'modal':true,'resize':function(event,ui){$(dialog).find('.xf-RecordBrowser-select-field').css('height',($(dialog).height()-60)+'px');}});rb.updateRecords();});},filterRecords:function(filter){for(var i in filter){if(this.filters[i]!=filter[i])this.dirty=true;this.filters[i]=filter[i];}
this.updateRecords();},updateRecords:function(){if(this.dirty){var sel=$(this.el).find('.xf-RecordBrowser-select-field');var val=$(sel).val();sel.load(this.getDataURL(),function(){sel.val(val);});this.dirty=false;}},getDataURL:function(){var url=DATAFACE_SITE_HREF+'?-action=RecordBrowser_data&-table='+encodeURIComponent(this.table);if(this.value)url+='&-value='+encodeURIComponent(this.value);if(this.text)url+='&-text='+encodeURIComponent(this.text);for(var i in this.filters){url+='&'+encodeURIComponent(i)+'='+encodeURIComponent(this.filters[i]);}
return url;}};$.fn.RecordBrowser=function(options){return this.each(function(){var obj=$(this);obj.click(function(){var rb=new xataface.RecordBrowser(options);rb.display();});});};$.fn.RecordBrowserWidget=function(options){return this.each(function(){var obj=$(this);if(obj.hasClass("xf-RecordBrowserWidget")){var oldDisplayField=obj.next();var oldButton=oldDisplayField.next();oldDisplayField.remove();oldButton.remove();obj.removeClass('xf-RecordBrowserWidget');}
var displayField=document.createElement('input');$(displayField).attr('type','text').addClass('xf-RecordBrowserWidget-displayField').css('cursor','pointer').attr('readonly',1);$(displayField).insertAfter(this);obj.css('display','none').addClass('xf-RecordBrowserWidget');if(!options.frozen){obj.change(function(){var id;if(options.value&&options.value!='__id__'){id=encodeURIComponent(options.value)+'='+encodeURIComponent(obj.val());}else{id=obj.val();}
var url=DATAFACE_SITE_HREF+'?-action=RecordBrowser_lookup_single&-table='+options.table+'&-id='+encodeURIComponent(id);if(options.text)url+='&-text='+encodeURIComponent(options.text);$.get(url,function(text){$(displayField).val(text);});});var a=document.createElement('a');$(a).addClass('xf-RecordBrowser-button').css('cursor','pointer').html('<img src="'+DATAFACE_URL+'/images/search_icon.gif" border="0" /><span class="xf-RecordBrowser-button-label"> Lookup</span>');$(a).find('.xf-RecordBrowser-button-label').css('display','none');$(a).insertAfter(displayField);if(!options.callback){options.callback=function(vals){for(var i in vals){obj.val(i);obj.trigger('change');}};}
$(a).RecordBrowser(options);$(displayField).RecordBrowser(options);}else{}
if(obj.val()){var id;if(options.value&&options.value!='__id__'){id=encodeURIComponent(options.value)+'='+encodeURIComponent(obj.val());}else{id=obj.val();}
var url=DATAFACE_SITE_HREF+'?-action=RecordBrowser_lookup_single&-table='+options.table+'&-id='+encodeURIComponent(id);if(options.text)url+='&-text='+encodeURIComponent(options.text);$.get(url,function(text){$(displayField).val(text);});}});};})(jQuery);